'use client';

import { useState } from 'react';
import { BarChart3, Loader2, TrendingUp, AlertCircle, Download, FileText, Share2 } from 'lucide-react';
import { analysisAPI } from '../../lib/api';
import { useToast } from '../../lib/toast';
import { SEOComparisonResult } from '../../lib/types';
import { exportSEOComparisonToCSV, exportSEOReportToPDF, shareReport } from '../../lib/export';
import { AnalysisResultSkeleton } from '../../lib/components/Skeleton';

export default function SEOComparison() {
  const { success, error: showError, info } = useToast();
  const [yourDomain, setYourDomain] = useState('');
  const [competitors, setCompetitors] = useState('');
  const [results, setResults] = useState<SEOComparisonResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [validationError, setValidationError] = useState('');

  const validateDomain = (domain: string): boolean => {
    const pattern = /^[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]?\.[a-zA-Z]{2,}$/;
    return pattern.test(domain.replace(/^https?:\/\//, '').replace(/\/.*$/, ''));
  };

  const compareSEO = async () => {
    setValidationError('');

    // Validation
    const cleanDomain = yourDomain.trim().replace(/^https?:\/\//, '').replace(/\/.*$/, '');
    if (!validateDomain(cleanDomain)) {
      setValidationError('Please enter a valid domain (e.g., example.com)');
      return;
    }

    const competitorList = competitors.split(',')
      .map(c => c.trim().replace(/^https?:\/\//, '').replace(/\/.*$/, ''))
      .filter(c => c && validateDomain(c));

    if (competitorList.length === 0) {
      setValidationError('Please enter at least one valid competitor domain');
      return;
    }

    setLoading(true);
    info('Starting Analysis', `Comparing ${cleanDomain} with ${competitorList.length} competitors...`);

    const { data, error } = await analysisAPI.seoComparison(cleanDomain, competitorList);

    if (error) {
      showError('Analysis Failed', error);
      setResults(null);
    } else if (data) {
      setResults(data);
      // Fix: Access nested data structure correctly
      const analysisData = data.data || data;
      success('Analysis Complete', `Analyzed ${analysisData?.your_site?.total_pages || 0} pages`);
    }

    setLoading(false);
  };

  // Helper to get the actual data (handles both nested and flat structures)
  const getAnalysisData = () => {
    if (!results) return null;
    // Handle double-nested structure from API wrapper
    return results.data?.data || results.data || results;
  };

  const analysisData = getAnalysisData();

  const handleExportCSV = () => {
    if (!analysisData) return;
    exportSEOComparisonToCSV(analysisData.your_site, analysisData.competitors, yourDomain);
    success('Exported', 'CSV file downloaded successfully');
  };

  const handleExportPDF = () => {
    if (!analysisData) return;
    exportSEOReportToPDF(
      analysisData.your_site,
      analysisData.competitors,
      analysisData.insights || [],
      yourDomain
    );
    success('Report Generated', 'PDF report opened in new tab');
  };

  const handleShare = async () => {
    if (!analysisData) return;
    const shared = await shareReport(
      `SEO Analysis - ${yourDomain}`,
      `SEO Score: ${analysisData.your_site?.avg_seo_score}/100\nPages: ${analysisData.your_site?.total_pages}\nGenerated by AI Grinners`
    );
    if (shared) {
      success('Shared', 'Report shared successfully');
    } else {
      info('Share', 'Sharing not supported on this device');
    }
  };

  return (
    <div className="p-4 lg:p-8 min-h-screen">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl lg:text-5xl font-bold mb-3 bg-gradient-to-r from-green-400 to-emerald-400 bg-clip-text text-transparent">
            SEO Comparison
          </h1>
          <p className="text-gray-200 text-lg">Side-by-side SEO metrics analysis</p>
        </div>

        {/* Form */}
        <div className="glass rounded-2xl p-6 lg:p-8 mb-8 border border-white/20">
          <div className="space-y-6">
            <div>
              <label className="block text-sm font-bold mb-3 text-green-300 flex items-center gap-2">
                <BarChart3 className="w-4 h-4" />
                Your Domain
              </label>
              <input
                type="text"
                value={yourDomain}
                onChange={(e) => { setYourDomain(e.target.value); setValidationError(''); }}
                placeholder="example.com"
                className="w-full p-4 bg-white/5 border border-white/20 rounded-xl text-white placeholder-gray-400 focus:border-green-400 focus:outline-none focus:ring-2 focus:ring-green-400/20 transition-all"
                disabled={loading}
              />
            </div>

            <div>
              <label className="block text-sm font-bold mb-3 text-emerald-300 flex items-center gap-2">
                <TrendingUp className="w-4 h-4" />
                Competitors (comma-separated)
              </label>
              <input
                type="text"
                value={competitors}
                onChange={(e) => { setCompetitors(e.target.value); setValidationError(''); }}
                placeholder="competitor1.com, competitor2.com"
                className="w-full p-4 bg-white/5 border border-white/20 rounded-xl text-white placeholder-gray-400 focus:border-emerald-400 focus:outline-none focus:ring-2 focus:ring-emerald-400/20 transition-all"
                disabled={loading}
              />
            </div>

            {validationError && (
              <div className="p-4 bg-red-500/10 border border-red-500/30 rounded-xl flex items-center gap-3 text-red-400">
                <AlertCircle className="w-5 h-5 flex-shrink-0" />
                <span className="text-sm">{validationError}</span>
              </div>
            )}
          </div>

          <button
            onClick={compareSEO}
            disabled={loading || !yourDomain || !competitors}
            className="mt-6 w-full bg-gradient-to-r from-green-600 to-emerald-600 text-white px-8 py-4 rounded-xl hover:shadow-2xl hover:shadow-green-500/50 font-bold text-lg transition-all flex items-center justify-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Analyzing...
              </>
            ) : (
              <>
                <BarChart3 className="w-5 h-5" />
                Compare SEO
              </>
            )}
          </button>
        </div>

        {/* Loading State */}
        {loading && <AnalysisResultSkeleton />}

        {/* Results */}
        {analysisData && !loading && (
          <div className="space-y-8">
            {/* Export Buttons */}
            <div className="flex flex-wrap gap-3">
              <button
                onClick={handleExportCSV}
                className="flex items-center gap-2 px-4 py-2 bg-green-500/10 hover:bg-green-500/20 text-green-400 rounded-xl transition-all border border-green-500/30"
              >
                <Download className="w-4 h-4" />
                Export CSV
              </button>
              <button
                onClick={handleExportPDF}
                className="flex items-center gap-2 px-4 py-2 bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 rounded-xl transition-all border border-blue-500/30"
              >
                <FileText className="w-4 h-4" />
                Export PDF
              </button>
              <button
                onClick={handleShare}
                className="flex items-center gap-2 px-4 py-2 bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 rounded-xl transition-all border border-purple-500/30"
              >
                <Share2 className="w-4 h-4" />
                Share
              </button>
            </div>

            {/* Your Site */}
            <div className="glass rounded-2xl p-6 lg:p-8 border-2 border-green-400/50">
              <h2 className="text-2xl lg:text-3xl font-bold mb-6 text-white">Your Site: {yourDomain}</h2>
              <div className="grid grid-cols-2 lg:grid-cols-5 gap-4 lg:gap-6">
                <div className="text-center p-4 bg-white/5 rounded-xl">
                  <div className="text-3xl lg:text-5xl font-bold text-green-400 mb-2">
                    {analysisData.your_site?.avg_seo_score || 0}
                  </div>
                  <div className="text-sm text-gray-300">SEO Score</div>
                </div>
                <div className="text-center p-4 bg-white/5 rounded-xl">
                  <div className="text-3xl lg:text-5xl font-bold text-blue-400 mb-2">
                    {analysisData.your_site?.total_pages || 0}
                  </div>
                  <div className="text-sm text-gray-300">Pages</div>
                </div>
                <div className="text-center p-4 bg-white/5 rounded-xl">
                  <div className="text-3xl lg:text-5xl font-bold text-purple-400 mb-2">
                    {analysisData.your_site?.avg_word_count || 0}
                  </div>
                  <div className="text-sm text-gray-300">Avg Words</div>
                </div>
                <div className="text-center p-4 bg-white/5 rounded-xl">
                  <div className="text-3xl lg:text-5xl font-bold text-orange-400 mb-2">
                    {analysisData.your_site?.avg_alt_coverage || 0}%
                  </div>
                  <div className="text-sm text-gray-300">Alt Coverage</div>
                </div>
                <div className="text-center p-4 bg-white/5 rounded-xl">
                  <div className="text-3xl lg:text-5xl font-bold text-pink-400 mb-2">
                    {analysisData.your_site?.schema_coverage || 0}%
                  </div>
                  <div className="text-sm text-gray-300">Schema</div>
                </div>
              </div>
            </div>

            {/* Competitors */}
            <div className="glass rounded-2xl p-6 lg:p-8">
              <h2 className="text-2xl lg:text-3xl font-bold mb-6 text-white">Competitors</h2>
              <div className="space-y-4">
                {Object.entries(analysisData.competitors || {}).map(([domain, data]: [string, any]) => (
                  <div key={domain} className="bg-white/5 p-4 lg:p-6 rounded-xl border border-white/10 hover:bg-white/10 transition-all">
                    <h3 className="font-bold text-lg lg:text-xl mb-4 text-white">{domain}</h3>
                    <div className="grid grid-cols-5 gap-2 lg:gap-4 text-center">
                      <div>
                        <div className="text-xl lg:text-3xl font-bold text-green-400">{data.avg_seo_score}</div>
                        <div className="text-xs text-gray-400 mt-1">Score</div>
                      </div>
                      <div>
                        <div className="text-xl lg:text-3xl font-bold text-blue-400">{data.total_pages}</div>
                        <div className="text-xs text-gray-400 mt-1">Pages</div>
                      </div>
                      <div>
                        <div className="text-xl lg:text-3xl font-bold text-purple-400">{data.avg_word_count}</div>
                        <div className="text-xs text-gray-400 mt-1">Words</div>
                      </div>
                      <div>
                        <div className="text-xl lg:text-3xl font-bold text-orange-400">{data.avg_alt_coverage}%</div>
                        <div className="text-xs text-gray-400 mt-1">Alt</div>
                      </div>
                      <div>
                        <div className="text-xl lg:text-3xl font-bold text-pink-400">{data.schema_coverage}%</div>
                        <div className="text-xs text-gray-400 mt-1">Schema</div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Insights */}
            {analysisData.insights?.length > 0 && (
              <div className="glass rounded-2xl p-6 lg:p-8 border-l-4 border-yellow-500">
                <h2 className="text-2xl lg:text-3xl font-bold mb-6 flex items-center gap-3 text-white">
                  <AlertCircle className="w-6 lg:w-8 h-6 lg:h-8 text-yellow-400" />
                  Insights
                </h2>
                <div className="space-y-3">
                  {analysisData.insights.map((insight: string, idx: number) => (
                    <div key={idx} className="flex items-start gap-3 bg-yellow-500/10 p-4 lg:p-5 rounded-xl border border-yellow-500/20">
                      <span className="text-yellow-400 font-bold text-lg lg:text-xl">→</span>
                      <span className="text-white text-base lg:text-lg">{insight}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Issues */}
            {analysisData.your_site?.issues?.length > 0 && (
              <div className="glass rounded-2xl p-6 lg:p-8 border-l-4 border-red-500">
                <h2 className="text-2xl lg:text-3xl font-bold mb-6 flex items-center gap-3 text-white">
                  <AlertCircle className="w-6 lg:w-8 h-6 lg:h-8 text-red-400" />
                  Issues Found
                </h2>
                <div className="space-y-3">
                  {analysisData.your_site.issues.map((issue: string, idx: number) => (
                    <div key={idx} className="flex items-start gap-3 bg-red-500/10 p-4 rounded-xl border border-red-500/20">
                      <span className="text-red-400">{issue}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Recommendations */}
            {analysisData.your_site?.recommendations?.length > 0 && (
              <div className="glass rounded-2xl p-6 lg:p-8 border-l-4 border-blue-500">
                <h2 className="text-2xl lg:text-3xl font-bold mb-6 flex items-center gap-3 text-white">
                  <TrendingUp className="w-6 lg:w-8 h-6 lg:h-8 text-blue-400" />
                  Recommendations
                </h2>
                <div className="space-y-3">
                  {analysisData.your_site.recommendations.map((rec: string, idx: number) => (
                    <div key={idx} className="flex items-start gap-3 bg-blue-500/10 p-4 rounded-xl border border-blue-500/20">
                      <span className="text-blue-400">{rec}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
